import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '@/app/_utils/styles/globals.scss';
import Header from '@/app/_components/molecules/Header/Header';
import { Footer } from '@/app/_components/molecules/Footer/Footer';

const inter = Inter({ subsets: ['latin'] });

// the metadata need to be updated dynamically according to the page
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
